[project]
name = "ai-scheduler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1",
    "pandas>=2.2",
    "plotly>=5.22",
    "streamlit>=1.38",
]
